# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bfdf5444d48a5f30d93123ec253f2ce21acf9840e518aa45197a88968985891378f76a3884b11e4aababba7e1054e08242af9b4a8e928a68f36c605aac91e22

test:
  secret_key_base: c376b09bdce1e3c8bbd64b2c44ee17cfdb15ef0f3da1f1913226d940aa6116a598e3a84821a31828e20a03d4c2057b121846e97eb5662d60a95403a87db279e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
